In [2]:
import pandas as pd
from database_engine import DatabaseFactory
import match_training as mt

INFO:database_engine:Database engine created successfully.

Current working directory: /Users/adamcarney/github-fs/asq-container/asq-front-end/backend

In [3]:
master_test_df = pd.read_excel('/Users/adamcarney/Downloads/respondent_large_master.xlsx')

In [4]:
master_test_df

,asq_test_filename,first_name,middle_name,last_name,birthdate,gender,race_ethnicity,street_address,city,state,...,personal_social_outcome,personal_social_recommendation,overall_test_score,referral,referral_concern,referral_agency,referral_followup_date,referral_source,referral_result,test_language
0,model_training_large.xlsx,Gabriello,Paulette,Folkes,2020-07-02,Male,Asian or Pacific Islander,76568 Pine View Lane,Chico,CA,...,Below Cutoff,Referral,140,True,Too Low,Test Referral Agency,2024-02-24,Test,Test,English
1,model_training_large.xlsx,Arnoldo,Melina,Terris,2019-12-04,Male,American Indian or Alaska Native,0 Dwight Court,Sacramento,CA,...,Below Cutoff,Referral,235,True,Too Low,Test Referral Agency,2023-10-22,Test,Test,English
2,model_training_large.xlsx,Emmett,Bartholomeus,Mattys,2023-12-24,Unknown,African American or Black,6813 Northland Terrace,Garden Grove,CA,...,Above Cutoff,NaN,156,True,Too Low,Test Referral Agency,2024-08-06,Test,Test,Spanish
3,model_training_large.xlsx,Tanhya,Kym,Trime,2021-06-19,Female,American Indian or Alaska Native,6995 Raven Trail,San Diego,CA,...,Below Cutoff,Referral,121,True,Too Low,Test Referral Agency,2024-08-22,Test,Test,Spanish
4,model_training_large.xlsx,Mitzi,Willamina,Lambswood,2023-11-06,Unknown,Two or More Races,7640 Claremont Parkway,Palo Alto,CA,...,Below Cutoff,Referral,169,True,Too Low,Test Referral Agency,2023-09-30,Test,Test,English
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,model_training_large.xlsx,Norry,Joanne,Duer,2020-07-27,Unknown,African American or Black,9 Claremont Plaza,Orange,CA,...,Below Cutoff,Referral,256,True,Too Low,Test Referral Agency,2023-12-05,Test,Test,Spanish
2496,model_training_large.xlsx,Dame,Willis,Janew,2023-09-22,Female,Hispanic,4227 Reindahl Center,Sacramento,CA,...,NaN,NaN,264,True,Too Low,Test Referral Agency,2023-09-30,Test,Test,English
2497,model_training_large.xlsx,Adriano,Dannie,Pagon,2023-03-30,Unknown,Hmong,9904 Ridgeway Center,Los Angeles,CA,...,Above Cutoff,NaN,267,True,Too Low,Test Referral Agency,2024-08-27,Test,Test,English
2498,model_training_large.xlsx,Ingrid,Enrico,Baccas,2020-06-25,Female,Asian or Pacific Islander,517 Moose Road,Long Beach,CA,...,Above Cutoff,NaN,313,True,Too Low,Test Referral Agency,2024-03-24,Test,Test,Spanish
2499,model_training_large.xlsx,Chandra,Twila,Heeron,2021-02-06,Female,Two or More Races,252 Paget Trail,Oakland,CA,...,Below Cutoff,Monitoring,261,True,Too Low,Test Referral Agency,2023-10-23,Test,Test,Spanish

In [5]:
# BEGIN: Modify first_name column based on the given condition
master_test_df['first_name'] = master_test_df['first_name'].apply(lambda x: x[0] if x[0] in ['A', 'D', 'F', 'R'] else x)
# END: Modify first_name column based on the given condition

master_test_df.head()

,asq_test_filename,first_name,middle_name,last_name,birthdate,gender,race_ethnicity,street_address,city,state,...,personal_social_outcome,personal_social_recommendation,overall_test_score,referral,referral_concern,referral_agency,referral_followup_date,referral_source,referral_result,test_language
0,model_training_large.xlsx,Gabriello,Paulette,Folkes,2020-07-02,Male,Asian or Pacific Islander,76568 Pine View Lane,Chico,CA,...,Below Cutoff,Referral,140,True,Too Low,Test Referral Agency,2024-02-24,Test,Test,English
1,model_training_large.xlsx,A,Melina,Terris,2019-12-04,Male,American Indian or Alaska Native,0 Dwight Court,Sacramento,CA,...,Below Cutoff,Referral,235,True,Too Low,Test Referral Agency,2023-10-22,Test,Test,English
2,model_training_large.xlsx,Emmett,Bartholomeus,Mattys,2023-12-24,Unknown,African American or Black,6813 Northland Terrace,Garden Grove,CA,...,Above Cutoff,NaN,156,True,Too Low,Test Referral Agency,2024-08-06,Test,Test,Spanish
3,model_training_large.xlsx,Tanhya,Kym,Trime,2021-06-19,Female,American Indian or Alaska Native,6995 Raven Trail,San Diego,CA,...,Below Cutoff,Referral,121,True,Too Low,Test Referral Agency,2024-08-22,Test,Test,Spanish
4,model_training_large.xlsx,Mitzi,Willamina,Lambswood,2023-11-06,Unknown,Two or More Races,7640 Claremont Parkway,Palo Alto,CA,...,Below Cutoff,Referral,169,True,Too Low,Test Referral Agency,2023-09-30,Test,Test,English

In [6]:
# BEGIN: Reverse month and day fields for specific birthdates
def reverse_month_day(date):
    if date.month in [12, 6, 2] and date.day < 12:
        return date.replace(month=date.day, day=date.month)
    return date

master_test_df['birthdate'] = master_test_df['birthdate'].apply(reverse_month_day)
# END: Reverse month and day fields for specific birthdates

master_test_df.head()

,asq_test_filename,first_name,middle_name,last_name,birthdate,gender,race_ethnicity,street_address,city,state,...,personal_social_outcome,personal_social_recommendation,overall_test_score,referral,referral_concern,referral_agency,referral_followup_date,referral_source,referral_result,test_language
0,model_training_large.xlsx,Gabriello,Paulette,Folkes,2020-07-02,Male,Asian or Pacific Islander,76568 Pine View Lane,Chico,CA,...,Below Cutoff,Referral,140,True,Too Low,Test Referral Agency,2024-02-24,Test,Test,English
1,model_training_large.xlsx,A,Melina,Terris,2019-04-12,Male,American Indian or Alaska Native,0 Dwight Court,Sacramento,CA,...,Below Cutoff,Referral,235,True,Too Low,Test Referral Agency,2023-10-22,Test,Test,English
2,model_training_large.xlsx,Emmett,Bartholomeus,Mattys,2023-12-24,Unknown,African American or Black,6813 Northland Terrace,Garden Grove,CA,...,Above Cutoff,NaN,156,True,Too Low,Test Referral Agency,2024-08-06,Test,Test,Spanish
3,model_training_large.xlsx,Tanhya,Kym,Trime,2021-06-19,Female,American Indian or Alaska Native,6995 Raven Trail,San Diego,CA,...,Below Cutoff,Referral,121,True,Too Low,Test Referral Agency,2024-08-22,Test,Test,Spanish
4,model_training_large.xlsx,Mitzi,Willamina,Lambswood,2023-11-06,Unknown,Two or More Races,7640 Claremont Parkway,Palo Alto,CA,...,Below Cutoff,Referral,169,True,Too Low,Test Referral Agency,2023-09-30,Test,Test,English

In [7]:
import re

def reverse_numbers(address):
    numbers = re.findall(r'\b\d+\b', address)
    for number in numbers:
        if 0 <= int(number) <= 200:
            reversed_number = number[::-1]
            address = address.replace(number, reversed_number)
    return address

master_test_df['street_address'] = master_test_df['street_address'].apply(reverse_numbers)

master_test_df.head()

,asq_test_filename,first_name,middle_name,last_name,birthdate,gender,race_ethnicity,street_address,city,state,...,personal_social_outcome,personal_social_recommendation,overall_test_score,referral,referral_concern,referral_agency,referral_followup_date,referral_source,referral_result,test_language
0,model_training_large.xlsx,Gabriello,Paulette,Folkes,2020-07-02,Male,Asian or Pacific Islander,76568 Pine View Lane,Chico,CA,...,Below Cutoff,Referral,140,True,Too Low,Test Referral Agency,2024-02-24,Test,Test,English
1,model_training_large.xlsx,A,Melina,Terris,2019-04-12,Male,American Indian or Alaska Native,0 Dwight Court,Sacramento,CA,...,Below Cutoff,Referral,235,True,Too Low,Test Referral Agency,2023-10-22,Test,Test,English
2,model_training_large.xlsx,Emmett,Bartholomeus,Mattys,2023-12-24,Unknown,African American or Black,6813 Northland Terrace,Garden Grove,CA,...,Above Cutoff,NaN,156,True,Too Low,Test Referral Agency,2024-08-06,Test,Test,Spanish
3,model_training_large.xlsx,Tanhya,Kym,Trime,2021-06-19,Female,American Indian or Alaska Native,6995 Raven Trail,San Diego,CA,...,Below Cutoff,Referral,121,True,Too Low,Test Referral Agency,2024-08-22,Test,Test,Spanish
4,model_training_large.xlsx,Mitzi,Willamina,Lambswood,2023-11-06,Unknown,Two or More Races,7640 Claremont Parkway,Palo Alto,CA,...,Below Cutoff,Referral,169,True,Too Low,Test Referral Agency,2023-09-30,Test,Test,English

In [8]:
def adjust_street_address(address):
    numbers = re.findall(r'\b\d+\b', address)
    for number in numbers:
        if 6000 <= int(number) <= 7000:
            adjusted_number = str(int(number) - 30)
            address = address.replace(number, adjusted_number)
    return address

master_test_df['street_address'] = master_test_df['street_address'].apply(adjust_street_address)

master_test_df.head()

,asq_test_filename,first_name,middle_name,last_name,birthdate,gender,race_ethnicity,street_address,city,state,...,personal_social_outcome,personal_social_recommendation,overall_test_score,referral,referral_concern,referral_agency,referral_followup_date,referral_source,referral_result,test_language
0,model_training_large.xlsx,Gabriello,Paulette,Folkes,2020-07-02,Male,Asian or Pacific Islander,76568 Pine View Lane,Chico,CA,...,Below Cutoff,Referral,140,True,Too Low,Test Referral Agency,2024-02-24,Test,Test,English
1,model_training_large.xlsx,A,Melina,Terris,2019-04-12,Male,American Indian or Alaska Native,0 Dwight Court,Sacramento,CA,...,Below Cutoff,Referral,235,True,Too Low,Test Referral Agency,2023-10-22,Test,Test,English
2,model_training_large.xlsx,Emmett,Bartholomeus,Mattys,2023-12-24,Unknown,African American or Black,6783 Northland Terrace,Garden Grove,CA,...,Above Cutoff,NaN,156,True,Too Low,Test Referral Agency,2024-08-06,Test,Test,Spanish
3,model_training_large.xlsx,Tanhya,Kym,Trime,2021-06-19,Female,American Indian or Alaska Native,6965 Raven Trail,San Diego,CA,...,Below Cutoff,Referral,121,True,Too Low,Test Referral Agency,2024-08-22,Test,Test,Spanish
4,model_training_large.xlsx,Mitzi,Willamina,Lambswood,2023-11-06,Unknown,Two or More Races,7640 Claremont Parkway,Palo Alto,CA,...,Below Cutoff,Referral,169,True,Too Low,Test Referral Agency,2023-09-30,Test,Test,English

In [8]:
database_factory = DatabaseFactory()
engine = database_factory.get_engine()

INFO:database_engine:Database engine created successfully.

In [9]:
master_test_df.to_sql('asq_test_details', engine, if_exists='append', index=False, schema='asq')

370

In [12]:
mt.process_file_matching("model_training_large.xlsx")

Predictor failed:
return dict at the end: {'Number of Partials': 1072}

Traceback (most recent call last):
  File "/Users/adamcarney/github-fs/asq-container/asq-front-end/backend/match_training.py", line 156, in process_matching
    linker.misc.save_model_to_json(model_name)
  File "/opt/homebrew/lib/python3.11/site-packages/splink/internals/linker_components/misc.py", line 46, in save_model_to_json
    raise ValueError(
ValueError: The path regular.json already exists. Please provide a different path or set overwrite=True

{'Number of Partials': 1072}

In [9]:
master_test_df.to_excel('/Users/adamcarney/Downloads/respondent_large_master_modified.xlsx', index=False)